version: '3.8'

services:
  solicy-backend:
    container_name: solicy-backend
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - solicy-backend-net
    depends_on:
      - db
    environment:
      DB_HOST: db
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    tty: true
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MOMERY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:SERVER_PORT/up}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
  db:
    container_name: db
    image: mysql
    networks:
      - solicy-backend-net
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - db:/var/lib/mysql
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
networks:
  solicy-backend-net:
volumes:
  db: